In [4]:
import pandas as pd

In [29]:
import numpy as np

In [36]:
import matplotlib.pyplot as plt

In [37]:
import seaborn as sns

In [38]:
df= pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/MPG.csv')

In [39]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [41]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [42]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [43]:
df.shape

(398, 9)

In [45]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

In [46]:
df=df.dropna()

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    object 
 8   name          392 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB


In [50]:
X=df[['displacement', 'horsepower', 'weight',
       'acceleration']]
y=df['mpg']

In [52]:
X.shape

(392, 4)

In [53]:
y.shape

(392,)

In [54]:
X

displacement  horsepower  weight  acceleration
0           307.0       130.0    3504          12.0
1           350.0       165.0    3693          11.5
2           318.0       150.0    3436          11.0
3           304.0       150.0    3433          12.0
4           302.0       140.0    3449          10.5
..            ...         ...     ...           ...
393         140.0        86.0    2790          15.6
394          97.0        52.0    2130          24.6
395         135.0        84.0    2295          11.6
396         120.0        79.0    2625          18.6
397         119.0        82.0    2720          19.4

[392 rows x 4 columns]

In [55]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
ss= StandardScaler()

In [58]:
X=ss.fit_transform(X)

In [59]:
X

array([[ 1.07728956,  0.66413273,  0.62054034, -1.285258  ],
       [ 1.48873169,  1.57459447,  0.84333403, -1.46672362],
       [ 1.1825422 ,  1.18439658,  0.54038176, -1.64818924],
       ...,
       [-0.56847897, -0.53247413, -0.80463202, -1.4304305 ],
       [-0.7120053 , -0.66254009, -0.41562716,  1.11008813],
       [-0.72157372, -0.58450051, -0.30364091,  1.40043312]])

In [60]:
pd.DataFrame(X).describe()

0             1             2             3
count  3.920000e+02  3.920000e+02  3.920000e+02  3.920000e+02
mean  -7.250436e-17 -1.812609e-16 -1.812609e-17  4.350262e-16
std    1.001278e+00  1.001278e+00  1.001278e+00  1.001278e+00
min   -1.209563e+00 -1.520975e+00 -1.608575e+00 -2.736983e+00
25%   -8.555316e-01 -7.665929e-01 -8.868535e-01 -6.410551e-01
50%   -4.153842e-01 -2.853488e-01 -2.052109e-01 -1.499869e-02
75%    7.782764e-01  5.600800e-01  7.510927e-01  5.384714e-01
max    2.493416e+00  3.265452e+00  2.549061e+00  3.360262e+00

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [62]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((294, 4), (98, 4), (294,), (98,))

In [63]:
from sklearn.linear_model import LinearRegression

In [64]:
lr= LinearRegression()

In [65]:
lr.fit(X_train,y_train)

LinearRegression()

In [66]:
lr.intercept_

23.272749238038443

In [67]:
lr.coef_

array([-0.68212355, -1.42604037, -4.41353455,  0.11501786])

In [68]:
y_pred=lr.predict(X_test)

In [69]:
y_pred

array([25.45757019, 30.43553822, 26.29100429, 25.57306421, 28.24760433,
       23.34101715, 29.4362264 , 29.72780069, 28.88232265, 27.19958697,
       26.89787592, 24.38004656, 18.5894287 , 30.31365204, 14.2447041 ,
       26.55486141, 30.69028895, 24.39867389, 17.10973861, 16.79124247,
       11.84434384, 29.68982825, 28.88573413, 30.05825128, 16.95790258,
       26.14335588, 30.17101117, 13.47571023, 23.52606759, 23.6257909 ,
       12.82339717, 31.25382787, 29.12530186, 24.87110481, 30.46754522,
       16.33390032, 21.64286892, 12.36072821, 28.68592865, 23.67542887,
       30.99896556, 28.88573413, 29.00920362, 28.30764118, 30.36754572,
       27.47483743, 24.00489783, 19.35047105, 28.91251044, 24.00258803,
       18.70422073, 22.18253945, 31.00717283,  7.91631588, 15.33568371,
       26.65488782, 12.42034872, 19.82544148, 20.18047699, 18.09300977,
       32.09138095, 29.16168906, 25.42226133, 25.59513673, 24.30977218,
       28.97358112, 22.77549601, 29.25986875, 25.39675434, 27.53

In [70]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

In [71]:
mean_absolute_error(y_test,y_pred)

3.295757829571128

In [72]:
mean_absolute_percentage_error(y_test,y_pred)

0.13691022351802362

In [73]:
mean_squared_error(y_test,y_pred)

18.564763012928324